#!/usr/bin/env python3
"""Assemble the /beatrix/ demo pages.

src/pages/*.html + src/partials/*.html + src/i18n.json  ->  ./*.html and js/i18n.js

- `{{> name}}` includes a partial; `{{home}}` is '' on the homepage and './' elsewhere; `{{v}}` is the
  cache stamp; `{{page.x}}` reads the page's front matter (`<!--page {json}-->` on the first line);
  `{{t:page.title}}` inserts the French string for the key named in that front-matter field.
- `{{logo:emblem,wordmark,signs}}` inlines the needed <path> definitions from assets/logo/elementa-logo.svg.
- Every element written as `<tag data-i18n="key"></tag>` gets the French text as its content, and
  `data-i18n-attr="alt:key|aria-label:key2"` gets those attributes, so the French page is complete
  without JavaScript. The runtime dictionary (both languages) is written to js/i18n.js.
- `{{faqld}}` builds the FAQPage JSON-LD from the faq.q*/faq.a* strings.

Bump VERSION whenever css/js change (the server caches assets for a year).
"""
import json, re, sys, html
from pathlib import Path

VERSION = '20260913a'
ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'src'

i18n = json.loads((SRC / 'i18n.json').read_text('utf8'))
fr, en = i18n['fr'], i18n['en']
missing = [k for k in fr if k not in en]
extra = [k for k in en if k not in fr]
if missing or extra:
    sys.exit(f'i18n mismatch: missing in en {missing}, extra in en {extra}')

partials = {p.stem: p.read_text('utf8') for p in (SRC / 'partials').glob('*.html')}
svg = (ROOT / 'assets/logo/elementa-logo.svg').read_text('utf8')

def svg_path(pid):
    m = re.search(r'<path id="%s"[^>]*/>' % re.escape(pid), svg)
    if not m:
        sys.exit(f'logo path {pid} not found')
    return m.group(0)

LOGO_SETS = {
    'emblem': ['p-emblem'],
    'wordmark': ['p-wordmark'],
    'signs': ['p-oval', 'p-sun', 'p-mountain', 'p-leaf', 'p-wave1', 'p-wave2', 'p-wave3'],
}

def logo_defs(spec):
    ids = []
    for name in spec.split(','):
        ids += LOGO_SETS[name.strip()]
    return ('<svg class="logo-defs" aria-hidden="true" focusable="false" width="0" height="0"><defs>'
            + ''.join(svg_path(i) for i in ids) + '</defs></svg>')

def strip_tags(s):
    return html.unescape(re.sub(r'<[^>]+>', '', s))

def faq_ld():
    qs = []
    for n in range(1, 20):
        q, a = fr.get(f'faq.q{n}'), fr.get(f'faq.a{n}')
        if not q:
            break
        qs.append({'@type': 'Question', 'name': q, 'acceptedAnswer': {'@type': 'Answer', 'text': strip_tags(a)}})
    data = {'@context': 'https://schema.org', '@type': 'FAQPage', 'mainEntity': qs}
    return '<script type="application/ld+json">' + json.dumps(data, ensure_ascii=False) + '</script>'

def fill_i18n(doc):
    def content(m):
        key = m.group(3)
        if key not in fr:
            sys.exit(f'missing i18n key {key}')
        return m.group(1) + fr[key] + m.group(4)
    doc = re.sub(r'(<(\w+)\b[^>]*\bdata-i18n="([^"]+)"[^>]*>)(</\2>)', content, doc)
    def attrs(m):
        out = [m.group(0)]
        for pair in m.group(1).split('|'):
            attr, key = pair.split(':', 1)
            if key not in fr:
                sys.exit(f'missing i18n key {key}')
            out.append(f' {attr}="{strip_tags(fr[key]).replace(chr(34), "&quot;")}"')
        return ''.join(out)
    return re.sub(r'data-i18n-attr="([^"]+)"', attrs, doc)

def build_page(path):
    raw = path.read_text('utf8')
    m = re.match(r'<!--page (\{.*?\})-->\n', raw, re.S)
    if not m:
        sys.exit(f'{path}: missing front matter')
    page = json.loads(m.group(1))
    doc = raw[m.end():]
    home = '' if page['id'] == 'home' else './'
    for _ in range(3):
        doc = re.sub(r'\{\{> (\w+)\}\}', lambda mm: partials[mm.group(1)], doc)
    doc = re.sub(r'\{\{t:page\.(\w+)\}\}', lambda mm: html.escape(fr[page[mm.group(1)]], quote=True), doc)
    doc = re.sub(r'\{\{page\.(\w+)\}\}', lambda mm: page.get(mm.group(1), ''), doc)
    doc = doc.replace('{{faqld}}', faq_ld())
    doc = re.sub(r'\{\{logo:([\w,]+)\}\}', lambda mm: logo_defs(mm.group(1)), doc)
    doc = doc.replace('{{home}}', home).replace('{{v}}', VERSION)
    doc = fill_i18n(doc)
    left = re.findall(r'\{\{[^}]+\}\}', doc)
    if left:
        sys.exit(f'{path}: unresolved tokens {left[:5]}')
    out = ROOT / path.name
    out.write_text(doc, 'utf8')
    print(f'{out.name}: {len(doc.encode())/1024:.0f} KB')

for p in sorted((SRC / 'pages').glob('*.html')):
    build_page(p)

js = ('/* generated by tools/build.py from src/i18n.json — do not edit by hand */\n'
      'window.ELEMENTA_I18N=' + json.dumps(i18n, ensure_ascii=False, separators=(',', ':')) + ';\n'
      'window.ELEMENTA_VERSION="' + VERSION + '";\n')
(ROOT / 'js/i18n.js').write_text(js, 'utf8')
print(f'js/i18n.js: {len(js.encode())/1024:.0f} KB, {len(fr)} keys')
