#!/usr/bin/env python3
"""Build the /vesplus/ demo pages.

- index.html is hand-authored (the motion home page); its navigation, menu, early-access band and footer are replaced
  between the NAV / MENU / EARLY / FOOTER markers from src/partials so every page shares one copy.
- src/pages/<name>.html holds the body of each secondary page (first line = front matter with the meta keys); it is
  wrapped in src/shell.html (head, logo defs taken from index.html, nav, menu, early-access band, footer, scripts).
- src/i18n.json (fr + en, one key per string) becomes js/i18n.js; French strings get the narrow no-break spaces
  before : ; ! ? at build time.
Run from anywhere: python3 tools/build.py. Bump VERSION for the ?v= stamps.
"""
import json, os, re, sys
VERSION = '20260919h'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src')
NB, NBSP = ' ', ' '

def fr_typo(s):
    s = re.sub(r' ([:;!?»])', NB + r'\1', s)
    s = re.sub(r'« ', '«' + NB, s)
    s = re.sub(r'(\d) h (\d)', rf'\1{NBSP}h{NBSP}\2', s)
    s = re.sub(r'(\d) (min|pi²|m²|pieds|po)\b', rf'\1{NBSP}\2', s)
    return s

def walk(v):
    if isinstance(v, str): return fr_typo(v)
    if isinstance(v, list): return [walk(x) for x in v]
    if isinstance(v, dict): return {k: walk(x) for k, x in v.items()}
    return v

def read(p):
    with open(p, encoding='utf-8') as f: return f.read()

def write(p, s):
    with open(p, 'w', encoding='utf-8') as f: f.write(s)

def region(html, name, replacement):
    a, b = f'<!-- {name}_START -->', f'<!-- {name}_END -->'
    i, j = html.index(a), html.index(b) + len(b)
    return html[:i] + a + '\n' + replacement.strip('\n') + '\n' + b + html[j:]

def inject(html, fr):
    """Write the French strings into the static markup so the page reads correctly before (or without) JavaScript."""
    def rep(m):
        tag, attrs, key = m.group(2), m.group(1), m.group(3)
        v = fr.get(key)
        if v is None or isinstance(v, list): return m.group(0)
        return f'{attrs}{v}</{tag}>'
    # simple elements: no nested element of the same tag inside an i18n element
    html = re.sub(r'(<(\w+)\b[^>]*\sdata-i18n="([^"]+)"[^>]*>)(?:(?!<\2\b).)*?</\2>', rep, html, flags=re.S)
    html = re.sub(r'(<(ul|ol)\b[^>]*\sdata-i18n-list="([^"]+)"[^>]*>)(.*?)(</\2>)', lambda m: m.group(1) + ''.join(f'<li>{x}</li>' for x in fr[m.group(3)]) + m.group(5), html, flags=re.S)
    html = re.sub(r'(<select\b[^>]*\sdata-i18n-options="([^"]+)"[^>]*>)(.*?)(</select>)', lambda m: m.group(1) + ''.join(f'<option>{x}</option>' for x in fr[m.group(2)]) + m.group(4), html, flags=re.S)
    def attr(html, dattr, target):
        def r(m):
            tag = m.group(0); key = m.group(1); v = fr.get(key)
            if v is None: return tag
            v = v.replace('"', '&quot;')
            if re.search(rf'\s{target}="[^"]*"', tag): return re.sub(rf'\s{target}="[^"]*"', f' {target}="{v}"', tag, count=1)
            return tag[:-1] + f' {target}="{v}">'
        return re.sub(rf'<[^>]*\s{dattr}="([^"]+)"[^>]*>', r, html)
    html = attr(html, 'data-i18n-alt', 'alt'); html = attr(html, 'data-i18n-aria', 'aria-label'); html = attr(html, 'data-i18n-ph', 'placeholder')
    return html

def main():
    i18n = json.load(open(os.path.join(SRC, 'i18n.json'), encoding='utf-8'))
    i18n['fr'] = walk(i18n['fr'])
    missing = [k for k in i18n['fr'] if k not in i18n['en']] + [k for k in i18n['en'] if k not in i18n['fr']]
    if missing: print('i18n keys without a pair:', missing); sys.exit(1)
    write(os.path.join(ROOT, 'js', 'i18n.js'), '// generated by tools/build.py from src/i18n.json — do not edit\nwindow.EL_I18N = ' + json.dumps(i18n, ensure_ascii=False, separators=(',', ':')) + ';\n')
    fr = i18n['fr']
    partials = {n: read(os.path.join(SRC, 'partials', n + '.html')) for n in ('nav', 'menu', 'early', 'footer', 'tour')}
    stamp = lambda s: re.sub(r'\?v=\d{8}[a-z]?', '?v=' + VERSION, s)
    # home page: shared regions + stamp
    index_path = os.path.join(ROOT, 'index.html'); index = read(index_path)
    for name in ('NAV', 'MENU', 'EARLY', 'FOOTER', 'TOUR'):
        index = region(index, name, partials[name.lower()].replace('{{HOME}}', ''))
    index = stamp(inject(index, fr)); write(index_path, index)
    defs = index[index.index('<!-- LOGO_DEFS_START -->'):index.index('<!-- LOGO_DEFS_END -->') + len('<!-- LOGO_DEFS_END -->')]
    # secondary pages
    shell = read(os.path.join(SRC, 'shell.html'))
    pages_dir = os.path.join(SRC, 'pages'); built = []
    for fn in sorted(os.listdir(pages_dir)):
        if not fn.endswith('.html'): continue
        body = read(os.path.join(pages_dir, fn))
        m = re.match(r'<!--\s*page:\s*(.*?)\s*-->\n', body)
        meta = dict(kv.split('=', 1) for kv in m.group(1).split()) if m else {}
        body = body[m.end():] if m else body
        key = meta.get('key', fn[:-5])
        html = shell.replace('{{LOGO_DEFS}}', defs).replace('{{TITLE}}', fr[f'meta.{key}.title']).replace('{{DESC}}', fr[f'meta.{key}.desc']).replace('{{KEY}}', key).replace('{{BODY}}', body.strip('\n')).replace('{{URL}}', fn)
        for name in ('NAV', 'MENU', 'EARLY', 'FOOTER', 'TOUR'):
            html = html.replace('{{' + name + '}}', partials[name.lower()].replace('{{HOME}}', 'index.html'))
        html = stamp(inject(html, fr)); write(os.path.join(ROOT, fn), html); built.append(fn)
    print('built', ', '.join(built), '| index.html regions refreshed | js/i18n.js', len(fr), 'keys | v=' + VERSION)

if __name__ == '__main__':
    main()
