#!/usr/bin/env python3
"""Assemble site/frames/{d,m}/<segment>/ from generated/seq/<segment>/{d,m}, write js/sequence.js
(segments + progress→frame keyframes) and the chapter posters.
Usage: build_sequence.py [--B B_descend|B_descend_sd] [--C C_shower|C_shower_sd]
"""
import argparse, glob, json, os, shutil
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEQ = os.path.join(os.path.dirname(ROOT), "generated", "seq")
OUT = os.path.join(ROOT, "frames")
ap = argparse.ArgumentParser(); ap.add_argument("--B", default="B_descend"); ap.add_argument("--C", default="C_shower"); a = ap.parse_args()

# journey order: real clips + fal.ai bridges
order = ["intro", "A_rise", "discovery", a.B, "enter", a.C, "shower", "D_porthole", "ladder", "E_rooftop", "F_night"]
ids = {"A_rise": "rise", a.B: "descend", a.C: "toshower", "D_porthole": "toporthole", "E_rooftop": "torooftop", "F_night": "night"}
segments = []
for sub in ("d", "m"):
    shutil.rmtree(f"{OUT}/{sub}", ignore_errors=True)
for src in order:
    sid = ids.get(src, src); n = None
    for sub in ("d", "m"):
        files = sorted(glob.glob(f"{SEQ}/{src}/{sub}/*.webp")); assert files, f"missing {src}/{sub}"
        dst = f"{OUT}/{sub}/{sid}"; os.makedirs(dst, exist_ok=True)
        for i, f in enumerate(files, 1): shutil.copy(f, f"{dst}/f_{i:03d}.webp")
        n = len(files)
    segments.append({"id": sid, "n": n})
starts = {}; c = 0
for s in segments: starts[s["id"]] = c; c += s["n"]
total = c
F = lambda sid, t=0.0: starts[sid] + (segments[[s["id"] for s in segments].index(sid)]["n"] - 1) * t
end = lambda sid: F(sid, 1.0)
# progress → frame. Holds sit under the four text windows (see config.js CHAPTERS).
keyframes = [
    [0.00, F("intro", 0.0)],
    [0.13, end("intro")],          # 1 INTRODUCTION: near-still deck shot drifts while the first text reads
    [0.22, end("rise")],           #   rise over the roof
    [0.36, end("discovery")],      # 2 DISCOVERY: pull out over the forest
    [0.43, end("discovery")],      #   hold on the wide view
    [0.49, end("descend")],        #   drop into the canopy
    [0.56, end("enter")],          # 3 DETAIL: in through the window, the room, the porthole hallway
    [0.605, end("toshower")],
    [0.655, end("shower")],
    [0.70, end("toporthole")],
    [0.745, end("ladder")],        #   porthole, ladder, room
    [0.815, end("torooftop")],     #   up to the rooftop
    [0.905, end("night")],         # 4 INVITATION: night falls
    [1.00, end("night")],
]
keyframes = [[p, round(f, 2)] for p, f in keyframes]
js = "/* generated by tools/build_sequence.py */\nexport const SEQUENCE = " + json.dumps({"segments": segments, "total": total, "keyframes": keyframes}, indent=1) + ";\n"
open(f"{ROOT}/js/sequence.js", "w").write(js)
# posters (desktop frame → jpg 1600px)
posters = {"intro": ("intro", 1), "discovery": ("discovery", 60), "detail": ("shower", 20), "invitation": ("night", 48)}
for name, (sid, k) in posters.items():
    im = Image.open(f"{OUT}/d/{sid}/f_{k:03d}.webp").convert("RGB"); im.thumbnail((1600, 1600))
    im.save(f"{ROOT}/assets/poster-{name}.jpg", quality=80, optimize=True, progressive=True)
size = lambda sub: sum(os.path.getsize(f) for f in glob.glob(f"{OUT}/{sub}/**/*.webp", recursive=True)) / 1e6
print("segments:", [(s["id"], s["n"]) for s in segments]); print("total frames:", total)
print(f"desktop {size('d'):.1f} MB, mobile {size('m'):.1f} MB")
